docker create \
    --name sonarr \
    -p 8989:8989 \
    -e PUID=<UID> -e PGID=<GID> \
    -e TZ=central \ 
    -v </path/to/appdata>:/config \
    -v <path/to/tvseries>:/tv \
    -v <path/to/downloadclient-downloads>:/downloads \
    linuxserver/sonarr