---
# tasks file for wg_vpn
# playbook to go from a "base configured" server to a wg vpn peer
- hosts: vpn
  remote_user: josiah
  gather_facts: false
  vars:
    source_os: macos

  tasks:
    - name: generate config on relay server
      include: pretasks_debian.yml
      become: yes      
    - name: generate config on local mac
      include: pretasks_mac.yml
      delegate_to: localhost
      when: source_os == 'macos'      
    - name: generate config for IOS on local mac
      include: pretasks_ios.yml
      delegate_to: localhost
      
    - name: complete config, wg up on relay server
      include: posttasks_debian.yml
      become: yes
    - name: complete config, wg up on local mac
      include: posttasks_mac.yml
      delegate_to: localhost
      when: source_os == 'macos'
    - name: complete config for IOS on local mac
      include: posttasks_mac.yml
      delegate_to: localhost      

