all:
  children:
    prod:
      hosts:
        # 10.30.12.41 is the secops-utils ip
        monitoring.awful.club:
          ansible_user: josiah
          ansible_timeout: 100
    dev:
      hosts:
        localhost:
