all:
  children:
    dockerhosts:
      hosts:
        awful-1.awful.club:
    vpn:
      hosts:
        vpn.awful.club:
    dev:
      hosts:
        localhost:
    onprem:
      hosts:
        hatchery:
